(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var jKa=function(a){a=String(a);var b=a.indexOf(".");-1==b&&(b=a.length);return(0,g.KFa)("0",Math.max(0,2-b))+a},kKa=function(){return{D:"svg",
V:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},S:[{D:"path",V:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},lKa=function(){return{D:"svg",
V:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},S:[{D:"path",V:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},j4=function(a){"number"===typeof a?(this.date=mKa(a,0,1),i4(this,1)):g.Ma(a)?(this.date=mKa(a.getFullYear(),a.getMonth(),a.getDate()),i4(this,a.getDate())):(this.date=new Date(g.Ra()),a=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),i4(this,a))},mKa=function(a,b,c){b=new Date(a,b,c);
0<=a&&100>a&&b.setFullYear(b.getFullYear()-1900);return b},i4=function(a,b){a.getDate()!=b&&a.date.setUTCHours(a.date.getUTCHours()+(a.getDate()<b?1:-1))},k4=function(a,b){g.JM.call(this,a,{D:"div",
K:"ytp-reminder-menu",V:{role:"menu",tabindex:"-1"},S:[{D:"div",K:"ytp-reminder-menu-contents",S:[{D:"div",K:"ytp-reminder-menu-items"}]}]},100,!0);this.i=b;this.u=[];this.menuPopupRenderer=void 0;this.items=this.Ba("ytp-reminder-menu-items");this.hide()},oKa=function(a){var b=nKa(a),c=0,d={};
for(c=0;c<b.length;d={iy:d.iy},c++){var e=a.u[c];e||(e=new g.V({D:"div",K:"ytp-reminder-menu-item",V:{role:"menuitem",tabindex:"0"},S:[{D:"div",K:"ytp-reminder-menu-item-icon",oa:"{{icon}}"},{D:"div",K:"ytp-reminder-menu-item-label",oa:"{{text}}"}]}),d.iy=c,e.Qa("click",function(l){return function(){var m=l.iy;a.Bb();m=nKa(a)[m];a.W("reminderMenuItemClicked",m.serviceEndpoint||m.command)}}(d)),e.ya(a.items),a.u[c]=e);
var f=b[c],h=null;switch(f.icon&&f.icon.iconType){case "NOTIFICATIONS":h=kKa();break;case "NOTIFICATIONS_NONE":h=lKa();break;case "NOTIFICATIONS_ACTIVE":h=g.dK()}f=f.text?g.fw(f.text):"";e.update({icon:h,text:f})}for(;c<a.u.length;)a.u.pop().dispose();0===c?a.Bb():a.Sc(a.i)},nKa=function(a){return(a.menuPopupRenderer&&a.menuPopupRenderer.items||[]).reduce(function(b,c){c&&c.menuServiceItemRenderer&&b.push(c.menuServiceItemRenderer);
return b},[])},l4=function(a){g.V.call(this,{D:"div",
S:[{D:"button",Ca:["ytp-offline-slate-button","ytp-button"],S:[{D:"div",K:"ytp-offline-slate-button-icon",oa:"{{icon}}"},{D:"div",K:"ytp-offline-slate-button-text",oa:"{{text}}"}]}]});this.I=a;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.l=void 0;this.B=this.i=null;(this.C=this.Ba("ytp-offline-slate-button"))&&this.N(this.C,"click",this.G);this.hide()},pKa=function(a,b,c){!a.toggleButtonRenderer&&b&&b.toggleButtonRenderer?a.toggleButtonRenderer=b.toggleButtonRenderer:
b&&b.toggleButtonRenderer||(a.toggleButtonRenderer=null);
!a.upcomingEventReminderButtonRenderer&&c&&c.upcomingEventReminderButtonRenderer?a.upcomingEventReminderButtonRenderer=c.upcomingEventReminderButtonRenderer:c&&c.upcomingEventReminderButtonRenderer||(a.upcomingEventReminderButtonRenderer=null);m4(a)},m4=function(a){if(a.toggleButtonRenderer){var b=a.toggleButtonRenderer;
if(b.isToggled){var c=b.toggledText?g.fw(b.toggledText):"";a.update({text:c,icon:n4(b.toggledIcon)})}else c=b.defaultText?g.fw(b.defaultText):"",a.update({text:c,icon:n4(b.defaultIcon)});a.show()}else a.upcomingEventReminderButtonRenderer?(b=qKa(a))?(c=b.text?g.fw(b.text):"",a.update({text:c,icon:n4(b.icon)}),a.show()):a.hide():a.hide()},sKa=function(a,b,c){a.B||(a.B=new g.$t(a.I.T().gf));
var d={context:g.lr(a.B.config_||g.mr())};g.Gu()&&(d.context.clientScreenNonce=g.Gu());d.params=c;g.nr(a.B,b,d,{timeout:5E3,onSuccess:function(){a.upcomingEventReminderButtonRenderer&&a.l&&(a.upcomingEventReminderButtonRenderer.currentState=a.l,a.l=void 0)},
onError:function(){rKa(a)},
onTimeout:function(){rKa(a)}})},rKa=function(a){a.toggleButtonRenderer?(a.toggleButtonRenderer.isToggled=!a.toggleButtonRenderer.isToggled,m4(a)):a.upcomingEventReminderButtonRenderer&&(a.l=void 0,m4(a))},n4=function(a){if(!a)return null;
switch(a.iconType){case "NOTIFICATIONS":return kKa();case "NOTIFICATIONS_NONE":return lKa();case "NOTIFICATIONS_ACTIVE":return g.dK();default:return null}},qKa=function(a){if(!a.upcomingEventReminderButtonRenderer)return null;
var b=a.l||a.upcomingEventReminderButtonRenderer.currentState;a=g.q(a.upcomingEventReminderButtonRenderer.states||[]);for(var c=a.next();!c.done;c=a.next())if((c=c.value.upcomingEventReminderButtonStateRenderer)&&c.state===b&&c.button&&c.button.buttonRenderer)return c.button.buttonRenderer;return null},o4=function(a){g.V.call(this,{D:"div",
K:"ytp-offline-slate",S:[{D:"div",K:"ytp-offline-slate-background"},{D:"div",K:"ytp-offline-slate-bar",S:[{D:"span",K:"ytp-offline-slate-icon",S:[{D:"svg",V:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},S:[{D:"path",V:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{D:"circle",V:{cx:"12",cy:"12",r:"3"}}]}]},{D:"span",K:"ytp-offline-slate-messages",S:[{D:"div",K:"ytp-offline-slate-main-text",V:{"aria-label":"{{label}}"},oa:"{{mainText}}"},{D:"div",K:"ytp-offline-slate-subtitle-text",oa:"{{subtitleText}}"}]},{D:"span",K:"ytp-offline-slate-buttons"}]},{D:"button",Ca:["ytp-offline-slate-close-button","ytp-button"],S:[g.ZJ()]},{D:"button",Ca:["ytp-offline-slate-open-button","ytp-button"],S:[g.YJ()]},{D:"div",K:"ytp-offline-slate-trailer-chip",oa:"Trailer"}]});var b=
this;this.api=a;this.i=this.l=null;this.background=this.Ba("ytp-offline-slate-background");this.u=this.Ba("ytp-offline-slate-bar");this.C=new g.J(function(){g.K(b.u,"ytp-offline-slate-bar-fade")},15E3);
this.G=!1;this.B=new g.J(function(){g.K(b.element,"ytp-offline-slate-collapsed")},15E3);
g.F(this,this.B);g.F(this,this.C);this.countdownTimer=new g.J(this.XJ,1E3,this);this.N(a,"presentingplayerstatechange",this.aK);this.N(a,"livestatedata",this.La);a=this.Ba("ytp-offline-slate-close-button");this.N(a,"click",function(){g.K(b.element,"ytp-offline-slate-collapsed")});
a=this.Ba("ytp-offline-slate-open-button");this.N(a,"click",function(){g.Bn(b.element,"ytp-offline-slate-collapsed")});
this.hide();a=this.getVideoData();a.getPlayerResponse()&&(a=a.getPlayerResponse().playabilityStatus)&&this.La(a)},p4=function(a,b,c){var d,e,f,h;
if(b){var l=null!=b.subtitleText?g.fw(b.subtitleText):"";c=c?c:null!=b.mainText?g.fw(b.mainText):"";b=null!==(h=null===(f=null===(e=null===(d=b.mainText)||void 0===d?void 0:d.accessibility)||void 0===e?void 0:e.accessibilityData)||void 0===f?void 0:f.label)&&void 0!==h?h:c;a.update({mainText:c,subtitleText:l,label:b});g.L(a.element,"ytp-offline-slate-single-text-line",!l);g.L(a.u,"ytp-offline-slate-bar-hidden",!c&&!l)}},q4=function(a,b){var c=(0,g.P)();
this.trigger=a;this.i=b;this.u=c},s4=function(a){g.YL.call(this,a);
var b=this;this.J=!1;this.L=0;this.C=!1;this.l=new g.J(function(){var e=b.player.T(),f=b.getVideoData();if(r4(b))if(tKa(b)){var h;null!==(h=b.heartbeatParams)&&void 0!==h&&h.url&&(e=g.Hd(b.heartbeatParams.url,{request_id:g.yu()}),f.va&&(e=g.Hd(e,{vvt:f.va}),f.mdxEnvironment&&(e=g.Hd(e,{mdx_environment:f.mdxEnvironment}))),f.oauthToken&&(e=g.Hd(e,{access_token:f.oauthToken})),uKa(b,f,e))}else vKa(b),wKa(b,e,f)},0);
this.i=this.heartbeatParams=null;this.B=!1;this.G=new g.Nn(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.Y=new g.$t(void 0);this.U=this.attestationResponse=void 0;this.utcOffsetMinutes=-(new j4).date.getTimezoneOffset();this.u=new g.NL(this);g.F(this,this.l);g.F(this,this.u);vKa(this);xKa(this);this.u.N(a,"heartbeatparams",this.eM);this.u.N(a,"presentingplayerstatechange",this.fM);this.u.N(a,"videoplayerreset",this.gM);this.u.N(a,g.Zv("heartbeat"),this.xd);this.B&&this.i&&yKa(this,
this.i);var c=new g.Wv(1E3,0x7ffffffffffff,{priority:0,namespace:"heartbeat"}),d=new g.Wv(0x8000000000000,0x8000000000000,{id:"stream_end",priority:0,namespace:"heartbeat"});a.Bd([c,d])},vKa=function(a){var b=a.getVideoData();
b.rj&&g.roa(new g.ooa(b)).then(function(c){a.attestationResponse=c||void 0},function(){})},tKa=function(a){var b=a.getVideoData();
if(!g.dG(a.getVideoData())||b.jK)return!1;if(b.useInnertubeDrmService()&&b.G){a="playready"===b.G.flavor&&b.Z("html5_innertube_heartbeats_for_playready");var c="widevine"===b.G.flavor&&b.Z("html5_innertube_heartbeats_for_widevine");b=g.FC(b.G)&&b.Z("html5_innertube_heartbeats_for_fairplay");return!(a||c||b)}return!0},t4=function(a){if(tKa(a))return!!a.heartbeatParams;
var b=a.player.T(),c=a.getVideoData();return g.S(b.experiments,"html5_heartbeat_wait_for_drm_killswitch")||!g.dG(a.getVideoData())||!c.useInnertubeDrmService()||c.hf||c.Qz?!!c.heartbeatToken:!1},u4=function(a,b){if(!a.l.isActive()&&a.J){var c=a.getVideoData();
if(t4(a)||c.isLivePlayback){if(void 0===b)if(a.C){var d;b=a.B?7500:(null===(d=a.heartbeatParams)||void 0===d?0:d.interval)?1E3*a.heartbeatParams.interval:a.getVideoData().JI||6E4}else b=1E3;a.l.start(b)}}},uKa=function(a,b,c){b.jj&&(c=g.Hd(c,{internalipoverride:b.jj}));
var d={cpn:b.clientPlaybackNonce};b.contextParams&&(d.context_params=b.contextParams);b.Za&&(d.kpt=b.Za);c=g.Hd(c,d);g.sp(c,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(e){if(!a.l.isActive()&&r4(a)){a.G.reset();a.sequenceNumber++;e=e.responseText;var f=zKa(e);if(f){a.player.Ma("onHeartbeat",f);var h="ok"===f.status?f.stop_heartbeat?2:0:"stop"===f.status?1:"live_stream_offline"===f.status?0:-1}else h=(h=e.match(AKa))?"0"===h[1]?0:1:-1;BKa(a,f,e,h)}},
onError:function(e){r4(a)&&v4(a,!0,"net-"+e.status)},
onTimeout:function(){r4(a)&&v4(a,!0,"timeout")},
withCredentials:!0})},r4=function(a){var b=a.getVideoData();
return 3===a.player.getPresentingPlayerType()||g.U(a.player.sb(a.getPlayerType()),4)?!1:t4(a)||b.isLivePlayback?!0:(w4(a),!1)},wKa=function(a,b,c){var d,e={videoId:c.videoId,
sequenceNumber:a.sequenceNumber,heartbeatServerData:c.heartbeatServerData};a.U=a.attestationResponse;c.rj&&(e.attestationResponse={challenge:c.Aa,webResponse:a.U});var f=g.VL(c),h=null!==(d=f.client)&&void 0!==d?d:{};h.utcOffsetMinutes=a.utcOffsetMinutes;e.context=f;e.cpn=c.clientPlaybackNonce;if(f="undefined"!==typeof Intl?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)h.timeZone=f;h={heartbeatChecks:[]};if(f=c.getPlayerResponse())c.heartbeatToken&&(e.heartbeatToken=c.heartbeatToken),
(f=f.playabilityStatus)&&(f=f.liveStreamability)&&f.liveStreamabilityRenderer&&h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");c.heartbeatToken&&h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");g.bE(b)&&(h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED"),(b=a.player.getProgressState(a.getPlayerType()).ingestionTime)&&isFinite(b)&&(f={},f.clientPlayerPositionUtcMillis=""+Math.floor(1E3*b),h.unpluggedParams=f));e.heartbeatRequestParams=h;b={timeout:3E4,onSuccess:function(l){var m;
if(!a.l.isActive()&&r4(a)){var n=a.getVideoData(),p=n.rj&&null==a.U;n.rj=!(null===(m=l.heartbeatAttestationConfig)||void 0===m||!m.requiresAttestation)||p;m=l.playabilityStatus;n=JSON.stringify(m)||"{}";l.authenticationMismatch&&a.player.Ka("authshear","");p=-1;var r=l.playabilityStatus;r&&(a.player.Ma("onHeartbeat",r),"OK"===r.status?p=l.stopHeartbeat?2:0:"UNPLAYABLE"===r.status?p=1:"LIVE_STREAM_OFFLINE"===r.status&&(p=0));l=p;a.sequenceNumber&&-1===l||a.G.reset();a.sequenceNumber++;BKa(a,m,n,l)}},
onError:function(l){r4(a)&&v4(a,!0,"net-"+l.status)},
onTimeout:function(){r4(a)&&v4(a,!0,"timeout")}};
c.Pe()&&(b.hF="Bearer "+c.Pe());g.nr(a.Y,"player/heartbeat",e,b)},BKa=function(a,b,c,d){-1===d?(b="decode "+g.vf(c),v4(a,!1,b)):2===d?(w4(a),a.C=!0):(a.L=0,a.l.stop(),1===d?(a.C=!1,a.player.Af("heartbeat.stop",a.Me(c)),g.vs("heartbeatActionPlayerHalted",CKa(b))):(a.C=!0,c=0,a.B&&b&&(c=yKa(a,b),a.player.W("livestatedata",b)),c?u4(a,c):u4(a)))},yKa=function(a,b){var c,d,e=b.liveStreamability&&b.liveStreamability.liveStreamabilityRenderer,f=!(!e||!e.switchStreamsImmediately),h=DKa(e),l=a.getVideoData(),
m=a.player.sb(a.getPlayerType()),n=m.qc()&&!g.iG(l)&&!a.player.isAtLiveHead(a.getPlayerType());
if(g.XF(l)){var p=(null===(c=a.player.pd())||void 0===c?void 0:c.Cb())||{};p.status=b.status||"";p.dvr=""+ +n;p["switch"]=""+ +f;p.ended=""+ +!(!e||!e.displayEndscreen);a.player.Ka("heartbeat",g.BB(p))}if(n&&!f)return h;f=e&&e.streamTransitionEndpoint&&e.streamTransitionEndpoint.watchEndpoint;if("STREAM_TRANSITION_TIMING_AT_STREAM_END"===(e&&e.transitionTiming))a.getVideoData().ZE=f;else{if(n=f)(n=f&&f.videoId)?(a.player.ej(n,void 0,void 0,!0,!0,f),a.Dw("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",
b),n=!0):n=!1;if(n)return h}if("OK"===b.status.toUpperCase()){f=e&&e.broadcastId;n=a.i&&a.i.liveStreamability&&a.i.liveStreamability.liveStreamabilityRenderer&&a.i.liveStreamability.liveStreamabilityRenderer.broadcastId;p=f!==n&&(null!=f||a.player.Z("web_player_heartbeat_undefined_killswitch"));if(!l.hlsvp&&!l.Na||p)return e={video_id:l.videoId},l.GB&&(e.is_live_destination="1"),a.player.Z("web_player_heartbeat_request_watch_next")||(e.disable_watch_next=!0,e.raw_watch_next_response=l.watchNextResponse),
e.autonav_state=l.autonavState,e.oauth_token=l.oauthToken,e.force_gvi=l.lf,e.Nh=l.Nh,8===a.player.getPresentingPlayerType()&&a.player.Om(8),m=void 0,l.hlsvp||l.Na?p&&(m=new q4("broadcastIdChanged",n+","+f),a.Dw("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",b)):(f&&(m=new q4("formatsReceived",""+f)),a.Dw("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",b)),a.player.loadVideoByPlayerVars(e,void 0,void 0,
void 0,m),h;a.player.zd("heartbeat",a.getPlayerType())}e&&e.displayEndscreen&&(a.offlineSlate?(a=a.offlineSlate,a.G=!0,a.vb&&a.api.hp()):g.dJ(m)&&(l=(null===(d=a.player.pd())||void 0===d?void 0:d.Cb())||{},a.player.Ka("hbse",g.BB(l),!0),a.player.hp(),a.player.Ma("onLiveMediaEnded",b)));return h},DKa=function(a){var b=0;
a&&a.pollDelayMs&&(a=Number(a.pollDelayMs))&&(b=a);return b},v4=function(a,b,c){if(!a.l.isActive()){a.l.stop();
a.L++;var d=a.getVideoData();if(d.dJ||b&&!g.dG(a.getVideoData())&&!t4(a)&&d.isLivePlayback)var e=!1;else{var f;(null===(e=a.heartbeatParams)||void 0===e?0:e.Ut)?f=a.heartbeatParams.Ut:f=d.YI||5;e=a.L>=f}e?(b?(b="heartbeat.net",e={enforcedPolicyToHaltOnNetworkFailure:!0}):(b="heartbeat.servererror",e=CKa()),g.vs("heartbeatActionPlayerHalted",e),(e=a.getVideoData())&&e.isLivePlayback?a.player.Af(b,"Video playback interrupted. Please try again.",c):a.player.Af(b,"Sorry, there was an error licensing this video.",
c)):(u4(a,a.G.getValue()),g.On(a.G))}},CKa=function(a){var b={enforcedPolicyToHaltOnNetworkFailure:!1};
a&&(b.serializedServerContext=a.additionalLoggingData);return b},w4=function(a){a.L=0;
a.l.stop();a.C=!1;a.sequenceNumber=0},xKa=function(a){var b,c=a.getVideoData(),d=a.player.T();
if(c.isLivePlayback)if(g.PC(d.B)){a.B=!0;a.J=!0;if(!g.MD(d)||g.bE(d))a.offlineSlate=new o4(a.player),g.F(a,a.offlineSlate),g.LL(a.player,a.offlineSlate.element,4);(c=c.getPlayerResponse())&&c.playabilityStatus&&(a.i=c.playabilityStatus);if("UNPLAYABLE"!==(null===(b=a.i)||void 0===b?void 0:b.status)||a.player.Z("stop_heartbeat_on_unplayable_live_videos_killswitch"))a.i?(c=DKa(a.i.liveStreamability&&a.i.liveStreamability.liveStreamabilityRenderer))?u4(a,c):u4(a,7500):u4(a,1E3)}else a.player.Af("html5.unsupportedlive",
"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");else!g.S(d.experiments,"html5_release_post_live_heartbeat_killswitch")&&g.fb(c.Y,"heartbeat")&&a.player.zd("heartbeat",a.getPlayerType())},zKa=function(a){try{var b=JSON.parse(a);
return null!=b?b:void 0}catch(c){}},EKa={ERAS:["BC",
"AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y",
"MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss a zzzz","h:mm:ss a z","h:mm:ss a","h:mm a"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5},x4=EKa;x4=EKa;g.k=j4.prototype;g.k.bG=x4.FIRSTDAYOFWEEK;g.k.cG=x4.FIRSTWEEKCUTOFFDAY;g.k.clone=function(){var a=new j4(this.date);a.bG=this.bG;a.cG=this.cG;return a};
g.k.getFullYear=function(){return this.date.getFullYear()};
g.k.getMonth=function(){return this.date.getMonth()};
g.k.getDate=function(){return this.date.getDate()};
g.k.set=function(a){this.date=new Date(a.getFullYear(),a.getMonth(),a.getDate())};
g.k.add=function(a){if(a.l||a.i){var b=this.getMonth()+a.i+12*a.l,c=this.getFullYear()+Math.floor(b/12);b%=12;0>b&&(b+=12);a:{switch(b){case 1:var d=0!=c%4||0==c%100&&0!=c%400?28:29;break a;case 5:case 8:case 10:case 3:d=30;break a}d=31}d=Math.min(d,this.getDate());this.date.setDate(1);this.date.setFullYear(c);this.date.setMonth(b);this.date.setDate(d)}a.days&&(a=new Date((new Date(this.getFullYear(),this.getMonth(),this.getDate(),12)).getTime()+864E5*a.days),this.date.setDate(1),this.date.setFullYear(a.getFullYear()),
this.date.setMonth(a.getMonth()),this.date.setDate(a.getDate()),i4(this,a.getDate()))};
g.k.toString=function(){return[this.getFullYear(),jKa(this.getMonth()+1),jKa(this.getDate())].join("")+""};
g.k.valueOf=function(){return this.date.valueOf()};g.v(k4,g.JM);k4.prototype.hide=function(){this.i&&this.i.removeAttribute("aria-haspopup");g.JM.prototype.hide.call(this)};
k4.prototype.show=function(){this.i&&this.i.setAttribute("aria-haspopup","true");g.JM.prototype.show.call(this)};
k4.prototype.ra=function(){g.zi(this.u);g.JM.prototype.ra.call(this)};g.v(l4,g.V);
l4.prototype.G=function(){if(this.toggleButtonRenderer){var a=this.toggleButtonRenderer;a.isToggled?this.u(a.toggledServiceEndpoint):this.u(a.defaultServiceEndpoint);a.isToggled=!a.isToggled;m4(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.i&&this.i.vb)this.i.Bb();else{var b=qKa(this);b&&this.u(b.serviceEndpoint||b.command);b=g.q(b&&b.command&&b.command.commandExecutorCommand&&b.command.commandExecutorCommand.commands||[]);for(var c=b.next();!c.done;c=b.next())if((c=c.value)&&c.openPopupAction&&
c.openPopupAction.popup&&c.openPopupAction.popup.menuPopupRenderer){a=c.openPopupAction.popup.menuPopupRenderer;break}this.i||(this.i=new k4(this.I,this.C),this.i.ya(this.element),g.F(this,this.i),this.i.subscribe("reminderMenuItemClicked",this.u,this));b=this.i;b.menuPopupRenderer=a;oKa(b)}};
l4.prototype.u=function(a){if(a&&(a.addUpcomingEventReminderEndpoint||a.removeUpcomingEventReminderEndpoint)){if(a.addUpcomingEventReminderEndpoint){var b=a.addUpcomingEventReminderEndpoint;var c="notification/add_upcoming_event_reminder"}else a.removeUpcomingEventReminderEndpoint&&(b=a.removeUpcomingEventReminderEndpoint,c="notification/remove_upcoming_event_reminder");if(c&&b&&b.params)for(sKa(this,c,b.params),a=g.q(b.commands||[]),b=a.next();!b.done;b=a.next())if((b=b.value)&&b.updateUpcomingEventReminderButtonStateCommand){this.l=
b.updateUpcomingEventReminderButtonStateCommand.state;m4(this);break}}};g.v(o4,g.V);g.k=o4.prototype;g.k.getPlayerType=function(){if(8===this.api.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.k.La=function(a){var b,c,d=null===(c=null===(b=null===a||void 0===a?void 0:a.liveStreamability)||void 0===b?void 0:b.liveStreamabilityRenderer)||void 0===c?void 0:c.offlineSlate;if(d){this.l=a;d=d.liveStreamOfflineSlateRenderer;d.canShowCountdown?this.XJ():p4(this,d);var e,f,h,l,m=null===(l=null===(h=null===(f=null===(e=null===a||void 0===a?void 0:a.liveStreamability)||void 0===e?void 0:e.liveStreamabilityRenderer)||void 0===f?void 0:f.offlineSlate)||void 0===h?void 0:h.liveStreamOfflineSlateRenderer)||
void 0===l?void 0:l.thumbnail;if(m){e=0;f=null;m=m.thumbnails;for(h=0;h<m.length;h++)m[h].width>e&&(e=m[h].width||0,f=m[h].url);f&&(this.background.style.backgroundImage="url("+f+")")}else this.background.style.backgroundImage="";d.actionButtons||d.reminderButton?(this.i||(this.i=new l4(this.api),this.i.ya(this.Ba("ytp-offline-slate-buttons")),g.F(this,this.i)),pKa(this.i,d.actionButtons&&d.actionButtons[0],d.reminderButton)):this.i&&pKa(this.i,null,null);this.l=a}else this.l=null;this.aK()};
g.k.aK=function(a){if(8===this.api.getPresentingPlayerType())var b=!0;else{var c=this.api.sb(),d=this.getVideoData();b=d.isLivePlayback&&(g.dJ(c)||g.U(c,2)||g.U(c,64));var e=2===d.autonavState&&g.U(c,2);c=c.qc()&&!g.iG(d)&&!this.api.isAtLiveHead(void 0,!0);b=b&&!c&&!e}if(b&&this.l)if(this.vb){if(null===a||void 0===a?0:g.oH(a,2))g.Bn(this.element,"ytp-offline-slate-collapsed"),this.B.stop(),g.Bn(this.u,"ytp-offline-slate-bar-fade"),this.C.start()}else a=8===this.api.getPresentingPlayerType()&&!this.getVideoData().Cj,
b=8===this.api.getPresentingPlayerType(),g.L(this.element,"ytp-offline-slate-premiere-trailer",a),g.L(this.element,"ytp-offline-slate-hide-background",b),this.show(),this.B.start(),this.api.W("offlineslatestatechange"),this.G&&this.api.hp();else this.vb&&(this.hide(),this.api.W("offlineslatestatechange"))};
g.k.XJ=function(){var a,b,c,d,e=null===(d=null===(c=null===(b=null===(a=this.l)||void 0===a?void 0:a.liveStreamability)||void 0===b?void 0:b.liveStreamabilityRenderer)||void 0===c?void 0:c.offlineSlate)||void 0===d?void 0:d.liveStreamOfflineSlateRenderer;if(e){var f=Math.floor(g.Ra()/1E3),h=e.canShowCountdown&&Number(e.scheduledStartTime);!h||h<=f?(p4(this,e),this.countdownTimer.stop()):(f=g.QK(h-f),p4(this,e,f),g.rn(this.countdownTimer))}};
g.k.ra=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.V.prototype.ra.call(this)};q4.prototype.l=function(a){return this.trigger&&a.trigger?this.trigger===a.trigger&&this.i===a.i:!1};
q4.prototype.isExpired=function(){return 6E4<(0,g.P)()-this.u};
q4.prototype.toString=function(){return"heartbeat:"+this.trigger+":"+this.i};g.v(s4,g.YL);g.k=s4.prototype;g.k.ra=function(){w4(this);this.player.Ve("heartbeat");g.YL.prototype.ra.call(this)};
g.k.xd=function(){this.J=!0;u4(this,2E3)};
g.k.eM=function(a){this.heartbeatParams=a;u4(this,2E3)};
g.k.fM=function(a){var b;8===this.player.getPresentingPlayerType()||"UNPLAYABLE"===(null===(b=this.i)||void 0===b?void 0:b.status)&&!this.player.Z("stop_heartbeat_on_unplayable_live_videos_killswitch")||(g.U(a.state,2)||g.U(a.state,64)?(w4(this),this.B&&(this.J=!0,u4(this,1E3))):(g.U(a.state,1)||g.U(a.state,8))&&u4(this,2E3))};
g.k.gM=function(){3!==this.player.getPresentingPlayerType()&&u4(this,2E3)};
g.k.getPlayerType=function(){if(8===this.player.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.k.Yh=function(a){switch(a){case 4:case 3:return!1}return!0};
g.k.Dw=function(a,b,c){a={trigger:a,reason:b};c&&(a.serializedServerContext=c.additionalLoggingData);g.vs("heartbeatActionPlayerTransitioned",a)};
g.k.Me=function(a){var b="LICENSE",c=zKa(a);if(c)return c.reason||g.DM[b]||"";(a=a.match(AKa))&&(a=Number(a[1]))&&(b=g.gla(a));return g.DM[b]||""};
g.k.ct=function(){return!!this.offlineSlate&&this.offlineSlate.vb};
var AKa=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.iM.heartbeat=s4;})(_yt_player);
